### ISSUE TITLE
can GPU 3090 run your code?

### ISSUE THREAD

**Issue by yuheyuan** [lhoyer/improving_segmentation_with_selfsupervised_depth#17]
I see your datasets need [leftImg8bit_sequence_trainvaltest.zip (324GB)](https://www.cityscapes-dataset.com/file-handling/?packageID=14) [[md5]](https://www.cityscapes-dataset.com/md5-sum/?packageID=14),it's too big.  I think my machine may spend long time to train a model.
So I want to know your machine use which gpu.

**Comment by lhoyer** [comment]
We have used a single Nvidia V100 for the training. It should be possible to run the code with an RTX 3090 as well. The size of the dataset does not matter in this regard as the model is trained on mini-batches that are loaded from the disk while training.
