### ISSUE TITLE
SSDA

### ISSUE THREAD

**Issue by gokling1219** [lhoyer/improving_segmentation_with_selfsupervised_depth#19]
Thank you for sharing. We are interested in SSDA, but we can't find the relevant part. Can you upload the training and testing code for SSDA? Thank you very much!

**Comment by lhoyer** [comment]
Please, checkout the `ssda` branch to see the relevant code and readme.

**Comment by gokling1219** [comment]
Sorry to bother you again. We did not find the SSDA branch in this project.

**Comment by gokling1219** [comment]
thank you！ we have found it！
