### ISSUE TITLE
error in run_experiments.py

### ISSUE THREAD

**Issue by AnukritiSinghh** [lhoyer/improving_segmentation_with_selfsupervised_depth#2]
Hi, thanks for this amazing work! 
When I run run_experiments.py I get the error 
`File "run_experiments.py", line 37, in <module>
    choices=MachineConfig.AVAIL_MACHINES
AttributeError: type object 'MachineConfig' has no attribute 'AVAIL_MACHINES'`

is there something missing? can I run run_experiments without running train.py first? Please help

**Comment by lhoyer** [comment]
I added the missing variable. It should work now.

**Comment by AnukritiSinghh** [comment]
Thank you!
I read that this automatic data selection method can be applied to any semantic segmentation method. Can you please guide what steps to follow for this? My dataset is not in the same format as Cityscapes.

**Comment by lhoyer** [comment]
In order to use our automatic data selection with another dataset, please have a look at the explanations in Issue #1.

**Comment by AnukritiSinghh** [comment]
Hello @lhoyer, Thankyou for the clarification. I was able to run exp 211 and get the selected labels. However, I am getting multiple json files with 744 and 25 selected labels. Can you please tell me why I am getting multiple files like this and each with entirely different labels? How do I know which label file is the best one to choose?

**Comment by lhoyer** [comment]
I'm glad to hear that. 

There is only one json file per number of labels supposed to be in the log directory as it is saved only once per configuration (see https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/label_selection.py#L137). If there had been another file with the same name in the directory, it would have been overridden. So, I don't see how multiple files with the same number of selected labels should end up in the same result directory. In that case, I would suggest deleting the log directory and rerunning the experiment.

If you mean that there are different directories each with a set of selected labels, these are different experiment configurations with different methods and random seeds. Please refer to https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/experiments.py#L242 for more details. The method we present in the paper with combined diversity and uncertainty sampling has the method abbreviation "depthifp_u3-avg4_bias1000ldepth_donly".
