### ISSUE TITLE
About paper presentations 

### ISSUE THREAD

**Issue by Renp1ngs** [lhoyer/improving_segmentation_with_selfsupervised_depth#20]
Dear hoyer:    
    I would very much like to know how those edges are drawn in the last column of Figure 5 of your conference paper. Hope to receive your reply.
    Best.

**Comment by lhoyer** [comment]
Dear @Renp1ngs,

For the visualization, we extract the edges from the mix mask, dilate them, and color the halves of the dilated edges according to the source image color code (orange/blue).

Best,
Lukas
