### ISSUE TITLE
Evaluating the model

### ISSUE THREAD

**Issue by testingshanu** [lhoyer/improving_segmentation_with_selfsupervised_depth#9]
Hi, 

Do you plan to provide the scripts to validate the final model?

Also in the paper I observed that evaluation metrics were mainly provided for semantic segmentation. I was curious to know if there was a comparison between the results of depth obtained from your network and "Digging into self-supervised monocular
depth estimation".

**Comment by testingshanu** [comment]
While saving the model, I get an error at https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/master/train.py#L362. 

The self.ema_model is not none as it enters this line - 
https://github.com/lhoyer/improving_segmentation_with_selfsupervised_depth/blob/1a6f4a88863602807d4192072ce5527c97a5b213/train.py#L282. 

Could you please provide the necessary changes to fix this issue ?

**Comment by lhoyer** [comment]
Hi,

The validation of the model is already part of the tensorboard logging. We do not use a separate validation script. We don't evaluate the depth estimation performance as we focus on semantic segmentation in this project.

If you want to store the model for inference, you can just remove the NotImplementedError. However, resuming training from a checkpoint is not supported.
